In [1]:
from rapidsegment import StrategicSegmentBuilder, StrategicSegmentScore, UniversalDataLoader

# Example Feature Groupings Setup
variable_groups = {
    "Demographics": [
        "age", 
        "gender", 
        "education_level", 
        "dependents", 
        "home_ownership", 
        "city_tier"
    ],
    "Employment": [
        "employment_type", 
        "years_employed"
    ],
    "Financial_Profile": [
        "annual_income", 
        "credit_score", 
        "existing_debt", 
        "account_balance", 
        "monthly_spend", 
        "loan_to_income_ratio", 
        "previous_defaults", 
        "number_of_cards"
    ],
    "Application_Details": [
        "requested_limit", 
        "application_channel"
    ]
}

# 2. Define your dynamically scaled optimization grid
my_search_grid = {
    "min_sample_size": [10000,5000, 1000, 500, 100],  # Example values for min_sample_size   
    "min_lift": [2.0,1.5]
}


# Initialize the builder
builder = StrategicSegmentBuilder(
    target="is_approved",
    # n_jobs=-1,
    min_sample_size=1000,
    min_lift=1.1,
    min_events = 5,
    top_n_vars=15,
    max_segments=10,
    enable_diversity=True,
    max_feature_reuse=1,
    enable_1way=True,  # Include 1-way rules from final output
    enable_2way=True,  # Exclude 2-way rules from final output
    enable_3way=True,  # Exclude 3-way rules from final output
    feature_groups=variable_groups,
    ignore_features=['application_id'],
    param_grid=my_search_grid,
    sort_priority = 'rate_lift_count'

)
data = UniversalDataLoader(file_path=r"/workspaces/RapidSegment/credit_app_data.parquet").load()

segments_df = builder.extract_segments(data)
final_eval = builder.evaluate_final_coverage(data)

2026-08-01 06:00:09,888 | INFO     | [data_loader.py:147] | 📂 Loading file: /workspaces/RapidSegment/credit_app_data.parquet (extension: .parquet)
2026-08-01 06:00:10,032 | INFO     | [builder.py:438] | 🚀 Starting hierarchical segment extraction...
2026-08-01 06:00:10,048 | INFO     | [builder.py:456] | ⚙️ DuckDB Configured: Threads=4/4, MemoryLimit=7GB
2026-08-01 06:00:10,048 | INFO     | [builder.py:461] | 📊 Sort priority: rate_lift_count
2026-08-01 06:00:11,170 | INFO     | [builder.py:161] | ✅ Feature group validation passed. (18 features mapped)
2026-08-01 06:00:11,171 | INFO     | [builder.py:485] | 📊 Dynamic Grid Search Enabled: 10 configurations.
2026-08-01 06:00:11,173 | INFO     | [builder.py:506] | 🔄 Iteration 1 | Remaining Volume: 500,000 | Base Rate: 26.79%
2026-08-01 06:00:11,173 | INFO     | [builder.py:238] | 🔍 Computing IV and bins for 18 features...
2026-08-01 06:00:19,854 | INFO     | [builder.py:698] | 📌 Feature Usage Tracker Update -> 'loan_to_income_ratio' used count = 1
2026-08-01 06:00:19,855 | INFO     | [builder.py:721] | ✅ Segment 1 Captured (Size Floor: 10000 | Lift Floor: 2.0): rows=44101, events=30741.0, lift=2.60
  Rule: loan_to_income_ratio=(-inf, 0.07)
  SQL: loan_to_income_ratio < 0.07
2026-08-01 06:00:21,179 | INFO     | [builder.py:506] | 🔄 Iteration 2 | Remaining Volume: 455,899 | Base Rate: 22.64%
2026-08-01 06:00:21,180 | INFO     | [builder.py:238] | 🔍 Computing IV and bins for 18 features...
2026-08-01 06:00:29,421 | INFO     | [builder.py:698] | 📌 Feature Usage Tracker Update -> 'credit_score' used count = 1
2026-08-01 06:00:29,422 | INFO     | [builder.py:721] | ✅ Segment 2 Captured (Size Floor: 10000 | Lift Floor: 2.0): rows=38924, events=21284.0, lift=2.41
  Rule: credit_score=[802.50, inf)
  SQL: credit_score >= 802.50
2026-08-01 06:00:30,962 | INFO     | [builder.py:506] | 🔄 Iteration 3 | Remaining Volume: 416,975 | Base Rate: 19.65%
2026-08-01 06:00:30,964 | INFO     | [builder.py:238] | 🔍 Computing IV and bins for 18 features...
2026-08-01 06:00:40,387 | INFO     | [builder.py:643] | ⏹️ No candidates cleared the grid. Stopping.
2026-08-01 06:00:40,416 | INFO     | [builder.py:757] | 🏁 Extraction complete.
2026-08-01 06:00:40,429 | INFO     | [builder.py:777] | 📊 Evaluating final hierarchical coverage on original data...

In [2]:
from prettytable import PrettyTable
import pandas as pd
table = PrettyTable()
table.field_names = list(pd.DataFrame(segments_df).columns)
for _, row in pd.DataFrame(segments_df).iterrows():
    table.add_row(list(row))
print(table)

+------------+-----------------------------------+-----------------------------+-------+-------------------+-------------------+--------------------------+-----------------------+
| segment_id |            rule_string            |          sql_filter         | count |        rate       |        lift       | meta_applied_sample_size | meta_applied_min_lift |
+------------+-----------------------------------+-----------------------------+-------+-------------------+-------------------+--------------------------+-----------------------+
|     1      | loan_to_income_ratio=(-inf, 0.07) | loan_to_income_ratio < 0.07 | 44101 |  69.7059023604907 | 2.601568361355638 |          10000           |          2.0          |
|     2      |     credit_score=[802.50, inf)    |    credit_score >= 802.50   | 38924 | 54.68091665810297 | 2.414943157235681 |          10000           |          2.0          |
+------------+-----------------------------------+-----------------------------+-------+-------------------+-------------------+--------------------------+-----------------------+

In [3]:

table = PrettyTable()
table.field_names = list(pd.DataFrame(final_eval).columns)
for _, row in pd.DataFrame(final_eval).iterrows():
    table.add_row(list(row))
print(table)

+---------+-------------+---------------+--------------------+--------------------+--------------+--------------------+
| segment | total_count | target_events |   response_rate    | base_response_rate | capture_rate |        lift        |
+---------+-------------+---------------+--------------------+--------------------+--------------+--------------------+
|   0.0   |   416975.0  |    81944.0    | 19.652017507044786 |      26.7938       |    83.395    | 0.7334539149745383 |
|   1.0   |   44101.0   |    30741.0    |  69.7059023604907  |      26.7938       |    8.8202    | 2.601568361355638  |
|   2.0   |   38924.0   |    21284.0    | 54.68091665810297  |      26.7938       |    7.7848    | 2.0408048376155294 |
+---------+-------------+---------------+--------------------+--------------------+--------------+--------------------+

In [4]:
print("--- FULL SEGMENT RULES ---\n")

for index, row in pd.DataFrame(segments_df).iterrows():
    print(f"Segment ID: {row['segment_id']}")
    print(f"Raw Rule:   {row['rule_string']}")
    print(f"SQL Filter: {row['sql_filter']}")
    print("-" * 50)

--- FULL SEGMENT RULES ---

Segment ID: 1
Raw Rule:   loan_to_income_ratio=(-inf, 0.07)
SQL Filter: loan_to_income_ratio < 0.07
--------------------------------------------------
Segment ID: 2
Raw Rule:   credit_score=[802.50, inf)
SQL Filter: credit_score >= 802.50
--------------------------------------------------

In [5]:
builder.explain_feature_journey("city_tier")

================================================================================
📌 AUDIT TRAIL FOR FEATURE: 'city_tier'
================================================================================

[Iteration 1]
  • Current dynamic IV   : 0.0047
  • Previous times used  : 0
  • Selection Status     : Eligible for Combination Search
  • Winner this round    : loan_to_income_ratio=(-inf, 0.07) (Variables: ['loan_to_income_ratio'])

[Iteration 2]
  • Current dynamic IV   : 0.0018
  • Previous times used  : 0
  • Selection Status     : Eligible for Combination Search
  • Winner this round    : credit_score=[802.50, inf) (Variables: ['credit_score'])

[Iteration 3]
  • Current dynamic IV   : 0.0027
  • Previous times used  : 0
  • Selection Status     : Eligible for Combination Search
================================================================================

In [6]:
# Preparing the dataset for scoring and decile banding.
import duckdb
conn = duckdb.connect()
predicted = conn.register("predicted", data)
predicted = conn.query("""
            SELECT *, 
            CASE WHEN loan_to_income_ratio < 0.07
            THEN 1 ELSE 0 END AS seg_1,
            CASE WHEN credit_score >= 802.50
            THEN 1 ELSE 0 END AS seg_2
            FROM predicted
""").df()
conn.close()

In [7]:
scorer = StrategicSegmentScore(
    target_col="is_approved",
    primary_key="application_id",
    segment_cols=["seg_1","seg_2"],
    weight_type = 'response',
)

In [8]:
model_artifact = scorer.calculate_and_export_weights(predicted)

2026-08-01 06:00:43,166 | INFO     | [scorer.py:76] | 🚀 Initialising out‑of‑core DuckDB scorecard engine...
2026-08-01 06:00:44,901 | INFO     | [scorer.py:118] | 📊 Computing scorecard weights...
2026-08-01 06:00:44,902 | WARNING  | [scorer.py:167] | ⚠️ DECILE RESOLUTION WARNING: Only 2 distinct non-zero score values found across 2 segments. Splitting into 10 deciles will produce repeated thresholds (e.g., top 5 deciles may have identical scores). For smooth decile ranking, ensure the builder discovers at least 10 distinct segments (increase `max_segments`). Consider interpreting results as tiers rather than deciles.
2026-08-01 06:00:44,903 | INFO     | [scorer.py:181] | ⚡ Scoring population natively via SQL engine...
2026-08-01 06:00:45,246 | INFO     | [scorer.py:201] | 📉 Dataset Zero‑Inflation Rate: 73.21%
2026-08-01 06:00:45,247 | INFO     | [scorer.py:206] | 📈 Calibrating deciles across active populations...
2026-08-01 06:00:45,263 | INFO     | [scorer.py:255] | ✅ Scorecard exported to: scored_experiment_2026_08_01_06_00_09.json

In [9]:
model_artifact.get("decile_min_thresholds")

{'1': 129,
 '2': 70,
 '3': 70,
 '4': 70,
 '5': 70,
 '6': 70,
 '7': 59,
 '8': 59,
 '9': 59,
 '10': 59}

In [10]:
for key, value in model_artifact.get("segment_weights").items():
    print(f"Segment: {key} | Weight: {value['weight']}")

Segment: seg_1 | Weight: 70
Segment: seg_2 | Weight: 59

In [11]:
conn = duckdb.connect()
scored = conn.register("scored", predicted)
scored = conn.query("""
WITH CTE AS (
    SELECT *, 
    CASE WHEN seg_1 = 1 THEN 79 ELSE 0 END AS seg_1_weighted,
    CASE WHEN seg_2 = 1 THEN 59 ELSE 0 END AS seg_2_weighted
    FROM scored),
    CTE2 AS (
    SELECT *, (seg_1_weighted + seg_2_weighted) AS total_weight
                     FROM CTE)
SELECT *, CASE WHEN total_weight >=129 THEN 1
                    WHEN total_weight >= 59 THEN 2
                    WHEN total_weight >= 0 THEN 3
                    WHEN total_weight >= 0 THEN 4
                    WHEN total_weight >= 0 THEN 5
                    WHEN total_weight >= 0 THEN 6
                    WHEN total_weight >= 0 THEN 7
                    WHEN total_weight >= 0 THEN 8
                    WHEN total_weight >= 0 THEN 9
                    WHEN total_weight >= 0 THEN 10
                    ELSE 0 END AS decile_band
                    
                     FROM CTE2
""").to_df()
conn.close()

In [12]:
conn = duckdb.connect()
scored = conn.register("scored", scored)
scored = conn.query("""SELECT decile_band, 
                    COUNT(*) AS count, 
                    SUM(is_approved) AS events, 
                    (SUM(is_approved)*100.0/COUNT(*)) AS response_rate
FROM scored
GROUP BY decile_band
ORDER BY decile_band
""").to_df()
conn.close()
scored

   decile_band   count   events  response_rate
0            1    3680   3640.0      98.913043
1            2   79345  48385.0      60.980528
2            3  416975  81944.0      19.652018

In [13]:
scorer = StrategicSegmentScore(
    target_col="is_approved",
    primary_key="application_id",
    segment_cols=["seg_1","seg_2"],
    weight_type = 'ln_response',
)
model_artifact = scorer.calculate_and_export_weights(predicted)
model_artifact.get("decile_min_thresholds")

2026-08-01 06:00:46,066 | INFO     | [scorer.py:76] | 🚀 Initialising out‑of‑core DuckDB scorecard engine...
2026-08-01 06:00:47,593 | INFO     | [scorer.py:118] | 📊 Computing scorecard weights...
2026-08-01 06:00:47,595 | WARNING  | [scorer.py:167] | ⚠️ DECILE RESOLUTION WARNING: Only 2 distinct non-zero score values found across 2 segments. Splitting into 10 deciles will produce repeated thresholds (e.g., top 5 deciles may have identical scores). For smooth decile ranking, ensure the builder discovers at least 10 distinct segments (increase `max_segments`). Consider interpreting results as tiers rather than deciles.
2026-08-01 06:00:47,595 | INFO     | [scorer.py:181] | ⚡ Scoring population natively via SQL engine...
2026-08-01 06:00:47,886 | INFO     | [scorer.py:201] | 📉 Dataset Zero‑Inflation Rate: 73.21%
2026-08-01 06:00:47,887 | INFO     | [scorer.py:206] | 📈 Calibrating deciles across active populations...
2026-08-01 06:00:47,903 | INFO     | [scorer.py:255] | ✅ Scorecard exported to: scored_experiment_2026_08_01_06_00_09.json

{'1': -36,
 '2': -36,
 '3': -36,
 '4': -36,
 '5': -36,
 '6': -54,
 '7': -54,
 '8': -54,
 '9': -54,
 '10': -54}

In [14]:
for key, value in model_artifact.get("segment_weights").items():
    print(f"Segment: {key} | Weight: {value['weight']}")

Segment: seg_1 | Weight: -36
Segment: seg_2 | Weight: -54

In [15]:
conn = duckdb.connect()
scored = conn.register("scored", predicted)
scored = conn.query("""
WITH CTE AS (
    SELECT *, 
    CASE WHEN seg_1 = 1 THEN -36 ELSE 0 END AS seg_1_weighted,
    CASE WHEN seg_2 = 1 THEN -54 ELSE 0 END AS seg_2_weighted
    FROM scored),
    CTE2 AS (
    SELECT *, (seg_1_weighted + seg_2_weighted) AS total_weight
                     FROM CTE)
SELECT *, CASE WHEN total_weight >=-36 THEN 1
                    WHEN total_weight >= -36 THEN 2
                    WHEN total_weight >= -36 THEN 3
                    WHEN total_weight >= -36 THEN 4
                    WHEN total_weight >= -36 THEN 5
                    WHEN total_weight >= -54 THEN 6
                    WHEN total_weight >= -54 THEN 7
                    WHEN total_weight >= -54 THEN 8
                    WHEN total_weight >= -54 THEN 9
                    WHEN total_weight >= -54 THEN 10
                    ELSE 0 END AS decile_band
                    
                     FROM CTE2
""").to_df()
conn.close()
conn = duckdb.connect()
scored = conn.register("scored", scored)
scored = conn.query("""SELECT decile_band, 
                    COUNT(*) AS count, 
                    SUM(is_approved) AS events, 
                    (SUM(is_approved)*100.0/COUNT(*)) AS response_rate
FROM scored
GROUP BY decile_band
ORDER BY decile_band
""").to_df()
conn.close()
scored

   decile_band   count    events  response_rate
0            0    3680    3640.0      98.913043
1            1  457396  109045.0      23.840392
2            6   38924   21284.0      54.680917

In [16]:
import duckdb
conn = duckdb.connect()

In [17]:
duckdb.query("""CREATE TABLE test AS 
SELECT 0 AS score FROM range(900) 
UNION ALL 
SELECT -floor(random()*30) - 1 AS score FROM range(100)""")

In [18]:
duckdb.query("""SELECT quantile_disc(score, [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0]) 
FROM test WHERE score > 0;  -- returns NULL or zeros""")

┌─────────────────────────────────────────────────────────────────────────────────────────┐
│ quantile_disc(score, main.list_value(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0)) │
│                                        double[]                                         │
├─────────────────────────────────────────────────────────────────────────────────────────┤
│ NULL                                                                                    │
└─────────────────────────────────────────────────────────────────────────────────────────┘

In [19]:
duckdb.query("""SELECT quantile_disc(score, [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0]) 
FROM test WHERE score != 0;  -- spreads negatives beautifully""").df()

  quantile_disc(score, main.list_value(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0))
0  [-25.0, -23.0, -21.0, -18.0, -16.0, -14.0, -11...